import {
  AlertTriangle,
  Cookie,
  Database,
  Eye,
  FileText,
  Globe,
  Lock,
  Mail,
  Share2,
  UserCheck,
} from "lucide-react";

export const sections = [
  {
    icon: FileText,
    title: "1. Introduction",
    content: [
      "Kunamix ('we', 'our', or 'us') is committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our services.",
      "We respect your privacy and are committed to protecting your personal data. This policy will inform you about how we handle your personal data, your privacy rights, and how the law protects you.",
      "By using our services, you consent to the collection and use of information in accordance with this Privacy Policy.",
    ],
    gradient: "from-blue-400 to-cyan-500",
  },
  {
    icon: Database,
    title: "2. Information We Collect",
    content: [
      "Personal Information: Name, email address, phone number, company name, billing address, and payment information when you engage our services.",
      "Project Information: Details about your project requirements, business objectives, and any content or materials you provide for project development.",
      "Technical Data: IP address, browser type, device information, operating system, and usage data collected through cookies and similar technologies.",
      "Communication Data: Records of correspondence, feedback, survey responses, and support inquiries.",
      "Referral Information: If you participate in our referral program, we collect information about referred clients with your consent.",
    ],
    gradient: "from-purple-400 to-pink-500",
  },
  {
    icon: Eye,
    title: "3. How We Use Your Information",
    content: [
      "Service Delivery: To provide, maintain, and improve our digital services including web development, mobile apps, and design solutions.",
      "Communication: To respond to inquiries, provide customer support, send project updates, and communicate about our services.",
      "Payment Processing: To process transactions, send invoices, and manage billing.",
      "Marketing: With your consent, to send promotional materials, newsletters, and information about new services. You can opt-out at any time.",
      "Analytics: To analyze usage patterns, improve our services, and enhance user experience.",
      "Legal Compliance: To comply with legal obligations and protect our rights and interests.",
      "Referral Program: To manage and process referral rewards and commissions.",
    ],
    gradient: "from-emerald-400 to-teal-500",
  },
  {
    icon: Lock,
    title: "4. Data Security",
    content: [
      "We implement industry-standard security measures to protect your personal information from unauthorized access, alteration, disclosure, or destruction.",
      "All sensitive data is encrypted using SSL/TLS protocols during transmission.",
      "We use secure servers and databases with restricted access to authorized personnel only.",
      "Regular security audits and updates are performed to maintain the highest security standards.",
      "Despite our efforts, no method of transmission over the internet is 100% secure. While we strive to protect your data, we cannot guarantee absolute security.",
      "In the event of a data breach, we will notify affected users in accordance with applicable laws.",
    ],
    gradient: "from-orange-400 to-red-500",
  },
  {
    icon: Share2,
    title: "5. Information Sharing & Disclosure",
    content: [
      "Service Providers: We may share information with trusted third-party service providers who assist in operating our business (payment processors, hosting providers, email services).",
      "Legal Requirements: We may disclose information if required by law, court order, or governmental request.",
      "Business Transfers: In the event of a merger, acquisition, or sale of assets, your information may be transferred to the new entity.",
      "With Your Consent: We may share information with third parties when you have given explicit consent.",
      "We do not sell, rent, or trade your personal information to third parties for marketing purposes.",
      "Portfolio & Marketing: With your permission, we may showcase your project in our portfolio and marketing materials.",
    ],
    gradient: "from-indigo-400 to-purple-500",
  },
  {
    icon: Cookie,
    title: "6. Cookies & Tracking Technologies",
    content: [
      "We use cookies and similar tracking technologies to enhance your experience on our website.",
      "Essential Cookies: Required for basic website functionality and security.",
      "Analytics Cookies: Help us understand how visitors interact with our website (Google Analytics, etc.).",
      "Marketing Cookies: Used to deliver relevant advertisements and track campaign effectiveness.",
      "You can control cookie preferences through your browser settings. Note that disabling cookies may affect website functionality.",
      "We use Google Analytics to analyze website traffic. You can opt-out using Google's opt-out tools.",
    ],
    gradient: "from-pink-400 to-rose-500",
  },
  {
    icon: UserCheck,
    title: "7. Your Privacy Rights",
    content: [
      "Access: You have the right to request access to the personal information we hold about you.",
      "Correction: You can request correction of inaccurate or incomplete personal data.",
      "Deletion: You may request deletion of your personal information, subject to legal obligations.",
      "Data Portability: You can request a copy of your data in a structured, machine-readable format.",
      "Opt-Out: You can opt-out of marketing communications at any time by clicking 'unsubscribe' in our emails.",
      "Withdraw Consent: You may withdraw consent for data processing where we rely on consent as the legal basis.",
      "To exercise these rights, please contact us at contact@kunamix.com.",
    ],
    gradient: "from-cyan-400 to-blue-500",
  },
  {
    icon: Globe,
    title: "8. International Data Transfers",
    content: [
      "Your information may be transferred to and processed in countries other than your country of residence.",
      "We ensure appropriate safeguards are in place to protect your data during international transfers.",
      "By using our services, you consent to the transfer of your information to India and other countries where we operate.",
      "We comply with applicable data protection laws regarding international data transfers.",
    ],
    gradient: "from-yellow-400 to-orange-500",
  },
  {
    icon: Database,
    title: "9. Data Retention",
    content: [
      "We retain your personal information only for as long as necessary to fulfill the purposes outlined in this Privacy Policy.",
      "Project-related data is typically retained for the duration of the project and for 3-5 years thereafter for legal and accounting purposes.",
      "Marketing data is retained until you opt-out or request deletion.",
      "After the retention period, we securely delete or anonymize your personal information.",
      "Some information may be retained for longer periods if required by law or for legitimate business purposes.",
    ],
    gradient: "from-red-400 to-pink-500",
  },
  {
    icon: AlertTriangle,
    title: "10. Third-Party Links",
    content: [
      "Our website may contain links to third-party websites, services, or applications.",
      "We are not responsible for the privacy practices of these third-party sites.",
      "We encourage you to review the privacy policies of any third-party sites you visit.",
      "This Privacy Policy applies only to information collected by Kunamix.",
    ],
    gradient: "from-green-400 to-emerald-500",
  },
  {
    icon: UserCheck,
    title: "11. Children's Privacy",
    content: [
      "Our services are not intended for children under the age of 18.",
      "We do not knowingly collect personal information from children under 18.",
      "If we become aware that we have collected data from a child under 18, we will take steps to delete such information.",
      "If you believe we have collected information from a child, please contact us immediately.",
    ],
    gradient: "from-violet-400 to-purple-500",
  },
  {
    icon: FileText,
    title: "12. Changes to Privacy Policy",
    content: [
      "We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements.",
      "We will notify you of any material changes by posting the new Privacy Policy on our website and updating the 'Last Updated' date.",
      "For significant changes, we may provide additional notice via email or prominent website notification.",
      "Your continued use of our services after changes become effective constitutes acceptance of the updated Privacy Policy.",
    ],
    gradient: "from-blue-400 to-indigo-500",
  },
  {
    icon: Mail,
    title: "13. Contact Us",
    content: [
      "If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:",
      "Email: contact@kunamix.com",
      "Data Protection Officer: dpo@kunamix.com",
      "Phone: +91 [Your Contact Number]",
      "Address: [Your Business Address]",
      "We will respond to your inquiry within 30 days.",
    ],
    gradient: "from-teal-400 to-cyan-500",
  },
];